- name: Installation Git
  hosts: vm_tests
  become: true
  tasks:
    - name: Überprüfung. Neue Packete
#     ansible.builtin.apt:
      ansible.builtin.dnf:
        update_cache: true

    - name: Wir installieren Git
#     ansible.builtin.apt:
      ansible.builtin.dnf:
        name: git
        state: present
