---
- name: Meine erste Schritte mit Ansible
  hosts: vm_tests
  become: true
  tasks:
    - name: Wir erstellen ein neues Verzeichnis
      ansible.builtin.file:
        path: /home/usecase_2025_01_10
        state: directory
        mode: '0755'
